

[functions.update-analytics-stats]
enabled = true
verify_jwt = true
import_map = "./functions/update-analytics-stats/deno.json"
entrypoint = "./functions/update-analytics-stats/index.ts"

[functions.identity-linking]
enabled = true
verify_jwt = true
import_map = "./functions/identity-linking/deno.json"
entrypoint = "./functions/identity-linking/index.ts"

[functions.update-storage-permissions]
enabled = true
verify_jwt = true
import_map = "./functions/update-storage-permissions/deno.json"
entrypoint = "./functions/update-storage-permissions/index.ts"

[functions.zenoti-connector]
enabled = true
verify_jwt = false
import_map = "./functions/zenoti-connector/deno.json"
